# -*- mode: ruby -*-

# The "2" in Vagrant.configure is for configuration version. Don't change it.
Vagrant.configure("2") do |config|
  config.vm.define "bxSandbox-deb11-desktop" do |guest|
    guest.vm.box = "debian-sandbox/testing64"    
    guest.vm.hostname = "bxSandbox-deb11"
    config.vm.provider :libvirt do |libvirt|
      libvirt.driver = "kvm"
    end
    ## SHELL PROVISIONING
    guest.vm.provision "shell", inline: <<-SHELL
      echo "
            ## STAGE 1: CREATE bxgenesis
      "
      shutdown now
      exit 0
SHELL
  end
end
